### PR TITLE
Clear source reader state on checkpointing

### LINKED ISSUE #30: Messages Not Cleared from Connector Once Acknowledged in Unbounded Mode
### Observed behavior

When messages are fetched from the consumer, they are passed to the NatsRecordEmitter via the SourceReaderBase, which adds them to the currentMessages list in the NatsSubjectSplit. The NatsSubjectSplit state is maintained in the SourceReaderBase, where it is used during snapshot creation, and messages are acknowledged either during checkpointing or through auto-acknowledgment.

However, in UNBOUNDED mode, once the messages are acknowledged, they are never cleared from the currentMessages list. This leads to unbounded growth of memory usage as the connector continues to run, potentially causing performance degradation or application failure due to excessive memory consumption.

### Expected behavior

Acknowledged messages should be removed from the currentMessages list to ensure memory is managed effectively, even in UNBOUNDED mode.

### Server and client version

nats-server 2.10.24
nats-cli 0.1.5
nats-flink-connector 2.0.0-beta4

### Host environment

MacOS

### Steps to reproduce

Enable debug logs in the connector or add a log in NatsJetStreamSourceReader.toSplitType to print the size of messages using natsSubjectSplitState.getSplit().getCurrentMessages().size()

Run SourceToSinkJsExample.java which publishes 10 messages to stream, these messages are never cleared from the connector state. They should ideally be cleared once acknowledged to ensure proper memory management.

### PR DESCRIPTION
**Pull request by tilakraj94**
This PR addresses the memory issue present in the main branch where the state maintained per source reader grows continuously with each call to the `snapshotState` method. In Flink, this method is invoked to take a snapshot of the state. However, the current implementation does not clear the messages from the state, even though they are acknowledged during the `notifyCheckpointComplete` phase.

To resolve this, we ensure that the state is cleared in a thread-safe manner, preventing unnecessary memory consumption.

**Below are logs illustrating the issue:**

```
2025-01-16 16:24:01:223+0530 [main] [DEBUG] NatsJetStreamSource - a0xg | Boundedness
2025-01-16 16:24:03:238+0530 [jobmanager-io-thread-1] [DEBUG] NatsJetStreamSource - 3ElD | getSplitSerializer
2025-01-16 16:24:03:265+0530 [jobmanager-io-thread-1] [DEBUG] NatsJetStreamSource - 3ElD | getEnumeratorCheckpointSerializer
2025-01-16 16:24:03:340+0530 [flink-akka.actor.default-dispatcher-6] [DEBUG] NatsJetStreamSource - 3ElD | createEnumerator
2025-01-16 16:24:03:341+0530 [flink-akka.actor.default-dispatcher-6] [DEBUG] NatsJetStreamSource - 3ElD | restoreEnumerator
2025-01-16 16:24:03:567+0530 [Source: nats-source-input -> Sink: Writer (1/1)#0] [DEBUG] NatsJetStreamSource - 3ElD | getSplitSerializer
2025-01-16 16:24:03:631+0530 [Source: nats-source-input -> Sink: Writer (1/1)#0] [DEBUG] NatsJetStreamSourceReader - a0xg-MCO02JyXx7 | start
2025-01-16 16:24:03:644+0530 [Source Data Fetcher for Source: nats-source-input -> Sink: Writer (1/1)#0] [DEBUG] NatsSubjectSplitReader - a0xg-MCO02JyXzf | handleSplitsChanges SplitAddition:[[[Subject: example-source]]]
2025-01-16 16:24:03:653+0530 [Source Data Fetcher for Source: nats-source-input -> Sink: Writer (1/1)#0] [INFO] NatsSubjectSplitReader - Register split [Subject: example-source] consumer for current reader.
2025-01-16 16:24:08:933+0530 [Source: nats-source-input -> Sink: Writer (1/1)#0] [DEBUG] NatsJetStreamSourceReader - a0xg-MCO02JyXx7 | Committing cursors for checkpoint 1
2025-01-16 16:24:08:933+0530 [Source: nats-source-input -> Sink: Writer (1/1)#0] [DEBUG] NatsSourceFetcherManager - No of messages to ack: 1000
2025-01-16 16:24:08:935+0530 [Source: nats-source-input -> Sink: Writer (1/1)#0] [DEBUG] NatsJetStreamSourceReader - a0xg-MCO02JyXx7 | Successfully acknowledge cursors for checkpoint 1
2025-01-16 16:24:18:898+0530 [Source: nats-source-input -> Sink: Writer (1/1)#0] [DEBUG] NatsJetStreamSourceReader - a0xg-MCO02JyXx7 | Committing cursors for checkpoint 2
2025-01-16 16:24:18:898+0530 [Source: nats-source-input -> Sink: Writer (1/1)#0] [DEBUG] NatsSourceFetcherManager - No of messages to ack: 1410
2025-01-16 16:24:18:902+0530 [Source: nats-source-input -> Sink: Writer (1/1)#0] [DEBUG] NatsJetStreamSourceReader - a0xg-MCO02JyXx7 | Successfully acknowledge cursors for checkpoint 2
2025-01-16 16:24:28:891+0530 [Source: nats-source-input -> Sink: Writer (1/1)#0] [DEBUG] NatsJetStreamSourceReader - a0xg-MCO02JyXx7 | Committing cursors for checkpoint 3
2025-01-16 16:24:28:891+0530 [Source: nats-source-input -> Sink: Writer (1/1)#0] [DEBUG] NatsSourceFetcherManager - No of messages to ack: 2010
2025-01-16 16:24:28:893+0530 [Source: nats-source-input -> Sink: Writer (1/1)#0] [DEBUG] NatsJetStreamSourceReader - a0xg-MCO02JyXx7 | Successfully acknowledge cursors for checkpoint 3
2025-01-16 16:24:38:889+0530 [Source: nats-source-input -> Sink: Writer (1/1)#0] [DEBUG] NatsJetStreamSourceReader - a0xg-MCO02JyXx7 | Committing cursors for checkpoint 4
2025-01-16 16:24:38:889+0530 [Source: nats-source-input -> Sink: Writer (1/1)#0] [DEBUG] NatsSourceFetcherManager - No of messages to ack: 2810
```

As seen in the logs, the number of messages to acknowledge keeps increasing with every fetch from the stream. Since this is an unbounded stream, the data retained in memory will continue to grow, leading to potential memory exhaustion.

### After PR Fix:

**Logs:**

```
2025-01-16 16:30:12:325+0530 [main] [DEBUG] NatsJetStreamSource - OU3Z | Boundedness
2025-01-16 16:30:13:436+0530 [jobmanager-io-thread-1] [DEBUG] NatsJetStreamSource - 61qx | getSplitSerializer
2025-01-16 16:30:13:441+0530 [jobmanager-io-thread-1] [DEBUG] NatsJetStreamSource - 61qx | getEnumeratorCheckpointSerializer
2025-01-16 16:30:13:476+0530 [flink-akka.actor.default-dispatcher-7] [DEBUG] NatsJetStreamSource - 61qx | createEnumerator
2025-01-16 16:30:13:476+0530 [flink-akka.actor.default-dispatcher-7] [DEBUG] NatsJetStreamSource - 61qx | restoreEnumerator
2025-01-16 16:30:13:614+0530 [Source: nats-source-input -> Sink: Writer (1/1)#0] [DEBUG] NatsJetStreamSource - 61qx | getSplitSerializer
2025-01-16 16:30:13:646+0530 [Source: nats-source-input -> Sink: Writer (1/1)#0] [DEBUG] NatsJetStreamSourceReader - OU3Z-dZWmh1o60N | start
2025-01-16 16:30:13:652+0530 [Source Data Fetcher for Source: nats-source-input -> Sink: Writer (1/1)#0] [DEBUG] NatsSubjectSplitReader - OU3Z-dZWmh1o63h | handleSplitsChanges SplitAddition:[[[Subject: example-source]]]
2025-01-16 16:30:13:657+0530 [Source Data Fetcher for Source: nats-source-input -> Sink: Writer (1/1)#0] [INFO] NatsSubjectSplitReader - Register split [Subject: example-source] consumer for current reader.
2025-01-16 16:30:20:793+0530 [Source: nats-source-input -> Sink: Writer (1/1)#0] [DEBUG] NatsJetStreamSourceReader - OU3Z-dZWmh1o60N | Committing cursors for checkpoint 1
2025-01-16 16:30:20:794+0530 [Source: nats-source-input -> Sink: Writer (1/1)#0] [DEBUG] NatsSourceFetcherManager - No of messages to ack: 1000
2025-01-16 16:30:20:797+0530 [Source: nats-source-input -> Sink: Writer (1/1)#0] [DEBUG] NatsJetStreamSourceReader - OU3Z-dZWmh1o60N | Successfully acknowledge cursors for checkpoint 1
2025-01-16 16:30:30:740+0530 [Source: nats-source-input -> Sink: Writer (1/1)#0] [DEBUG] NatsJetStreamSourceReader - OU3Z-dZWmh1o60N | Committing cursors for checkpoint 2
2025-01-16 16:30:30:740+0530 [Source: nats-source-input -> Sink: Writer (1/1)#0] [DEBUG] NatsSourceFetcherManager - No of messages to ack: 1000
2025-01-16 16:30:30:747+0530 [Source: nats-source-input -> Sink: Writer (1/1)#0] [DEBUG] NatsJetStreamSourceReader - OU3Z-dZWmh1o60N | Successfully acknowledge cursors for checkpoint 2
2025-01-16 16:30:40:736+0530 [Source: nats-source-input -> Sink: Writer (1/1)#0] [DEBUG] NatsJetStreamSourceReader - OU3Z-dZWmh1o60N | Committing cursors for checkpoint 3
2025-01-16 16:30:40:737+0530 [Source: nats-source-input -> Sink: Writer (1/1)#0] [DEBUG] NatsSourceFetcherManager - No of messages to ack: 1000
2025-01-16 16:30:40:739+0530 [Source: nats-source-input -> Sink: Writer (1/1)#0] [DEBUG] NatsJetStreamSourceReader - OU3Z-dZWmh1o60N | Successfully acknowledge cursors for checkpoint 3
2025-01-16 16:30:50:735+0530 [Source: nats-source-input -> Sink: Writer (1/1)#0] [DEBUG] NatsJetStreamSourceReader - OU3Z-dZWmh1o60N | Committing cursors for checkpoint 4
2025-01-16 16:30:50:736+0530 [Source: nats-source-input -> Sink: Writer (1/1)#0] [DEBUG] NatsSourceFetcherManager - No of messages to ack: 1000
2025-01-16 16:30:50:738+0530 [Source: nats-source-input -> Sink: Writer (1/1)#0] [DEBUG] NatsJetStreamSourceReader - OU3Z-dZWmh1o60N | Successfully acknowledge cursors for checkpoint 4
2025-01-16 16:31:00:735+0530 [Source: nats-source-input -> Sink: Writer (1/1)#0] [DEBUG] NatsJetStreamSourceReader - OU3Z-dZWmh1o60N | Committing cursors for checkpoint 5
2025-01-16 16:31:00:735+0530 [Source: nats-source-input -> Sink: Writer (1/1)#0] [DEBUG] NatsSourceFetcherManager - No of messages to ack: 293
2025-01-16 16:31:00:736+0530 [Source: nats-source-input -> Sink: Writer (1/1)#0] [DEBUG] NatsJetStreamSourceReader - OU3Z-dZWmh1o60N | Successfully acknowledge cursors for checkpoint 5
2025-01-16 16:31:10:740+0530 [Source: nats-source-input -> Sink: Writer (1/1)#0] [DEBUG] NatsJetStreamSourceReader - OU3Z-dZWmh1o60N | Committing cursors for checkpoint 6
2025-01-16 16:31:10:740+0530 [Source: nats-source-input -> Sink: Writer (1/1)#0] [DEBUG] NatsSourceFetcherManager - No of messages to ack: 0
2025-01-16 16:31:10:740+0530 [Source: nats-source-input -> Sink: Writer (1/1)#0] [DEBUG] NatsJetStreamSourceReader - OU3Z-dZWmh1o60N | Successfully acknowledge cursors for checkpoint 6
2025-01-16 16:31:20:736+0530 [Source: nats-source-input -> Sink: Writer (1/1)#0] [DEBUG] NatsJetStreamSourceReader - OU3Z-dZWmh1o60N | Committing cursors for checkpoint 7
2025-01-16 16:31:20:736+0530 [Source: nats-source-input -> Sink: Writer (1/1)#0] [DEBUG] NatsSourceFetcherManager - No of messages to ack: 0
2025-01-16 16:31:20:736+0530 [Source: nats-source-input -> Sink: Writer (1/1)#0] [DEBUG] NatsJetStreamSourceReader - OU3Z-dZWmh1o60N | Successfully acknowledge cursors for checkpoint 7
```

The logs confirm that the state is now cleared correctly, ensuring memory usage remains efficient and does not grow indefinitely. 

**PS:** _I had some 4293 messages and you can see the state is 0 once it stops receiving new messages._

Fixes #30

### CODE REVIEW

**Comment by scottf** [comment]
When does a split give it's messages to flink? Seems like that would be a good place. Maybe once it's acked. I'm not sure about this.

**Comment by tilakraj94** [comment]
The  `snapshotState(long checkpointId)` method is invoked asynchronously and performs the following operation:

```
public List<SplitT> snapshotState(long checkpointId) {
    List<SplitT> splits = new ArrayList<>();
    this.splitStates.forEach((id, context) -> 
        splits.add(this.toSplitType(id, context.state))
    );
    return splits;
}
```

In this process, the state is accessed, its messages are extracted, and the split is updated with the current state before being returned as a list of splits.

Once this method completes and returns, the `notifyCheckpointComplete` method is called to handle the acknowledgment of messages in the state.

To modify the state effectively, it seems necessary to have direct access to the state object itself.

**Comment by tilakraj9560** [comment]
```
private final Map<String, SplitContext<T, SplitStateT>> splitStates;

public void addSplits(List<SplitT> splits) {
    LOG.info("Adding split(s) to reader: {}", splits);
    splits.forEach((s) -> {
        SplitContext var10000 = (SplitContext)this.splitStates.put(s.splitId(), new SplitContext(s.splitId(), this.initializedState(s)));
    });
    this.splitFetcherManager.addSplits(splits);
}
```

The parent implementation of the source reader manages the **SplitContext** objects via the **splitStates** map. In the provided code snippet, we can observe that the **SplitContext** is controlled exclusively by the parent class. The **splitStates** map, which is private, is the central storage for these contexts and is populated using the **addSplits()** method.

The only way to access the **SplitContext** objects is indirectly through the **toSplitType** method, which adheres to Flink’s lifecycle management. This design ensures that the state and its transformations remain encapsulated and consistent with Flink’s internal state handling mechanisms.

**Comment by tilakraj94** [comment]
```
private final Map<String, SplitContext<T, SplitStateT>> splitStates;

public void addSplits(List<SplitT> splits) {
    LOG.info("Adding split(s) to reader: {}", splits);
    splits.forEach((s) -> {
        SplitContext var10000 = (SplitContext)this.splitStates.put(s.splitId(), new SplitContext(s.splitId(), this.initializedState(s)));
    });
    this.splitFetcherManager.addSplits(splits);
}
```

The parent implementation of the source reader manages the **SplitContext** objects via the **splitStates** map. In the provided code snippet, we can observe that the **SplitContext** is controlled exclusively by the parent class. The **splitStates** map, which is private, is the central storage for these contexts and is populated using the **addSplits()** method.

The only way to access the **SplitContext** objects is indirectly through the **toSplitType** method, which adheres to Flink’s lifecycle management. This design ensures that the state and its transformations remain encapsulated and consistent with Flink’s internal state handling mechanisms.

File: src/main/java/io/synadia/flink/v0/source/split/NatsSubjectSplitState.java [hunk 1]
```diff
@@ -11,8 +16,20 @@ public NatsSubjectSplitState(NatsSubjectSplit split) {
...
+    // so even if they fail by some reason in later stages, they will be re-delivered by NATS
     public NatsSubjectSplit toNatsSubjectSplit() {
-        return new NatsSubjectSplit(split.getSubject(), split.getCurrentMessages());
+        List<Message> messages = new ArrayList<>(split.getCurrentMessages());
+
+        // this resets the state to hold new messages
+        split.getCurrentMessages().clear();
+
+        // return the messages for acknowledgment and store them in state backends
+        return new NatsSubjectSplit(split.getSubject(), messages);
```
Comment (scottf) [inline src/main/java/io/synadia/flink/v0/source/split/NatsSubjectSplitState.java:32]: Is there a reason to make a new split? Why not just return existing split and clean it up? It would be different if the split state did not have a copy of the split. Maybe the split state should only have a copy of the messages, the state?

Comment (tilakraj94) [reply src/main/java/io/synadia/flink/v0/source/split/NatsSubjectSplitState.java:32]: Each split has a one-to-one mapping with its state, meaning every state instance references a specific split object. Therefore, we cannot return the same split object directly, as we need to clear its state to hold a new set of messages.

The state is initialized with the following method on add reader:

```
protected NatsSubjectSplitState initializedState(NatsSubjectSplit natsSubjectSplit) {
    return new NatsSubjectSplitState(natsSubjectSplit);
}
```

To avoid conflicts, we create and return a new split object. If you examine the parent caller of this method:

```
public List<SplitT> snapshotState(long checkpointId) {
    List<SplitT> splits = new ArrayList<>();
    this.splitStates.forEach((id, context) -> splits.add(this.toSplitType(id, context.state)));
    return splits;
}
```

The snapshotState method collects splits into a local variable and returns them. These splits hold the messages that will be acknowledged during the notifyCheckpointComplete phase. By creating a new split object, we ensure that the state of the original split can be safely cleared and updated for new messages, without affecting the checkpointing or acknowledgment process.

Comment (tilakraj94) [reply src/main/java/io/synadia/flink/v0/source/split/NatsSubjectSplitState.java]: i agree we can pass the same split. made changes to the code.

**Comment by sourabhaggrawal** [comment]
LGTM
